//! Standalone HTML dashboard export.

use anyhow::{Context, Result};
use serde_json::json;
use std::fs::File;
use std::io::Write;
use std::path::Path;

use crate::engine::TraceAnalysis;
use crate::model::Trace;
use crate::report::sampling_note;

/// Plotly bundle embedded so the report renders without network access.
const PLOTLY_JS: &str = include_str!("../../assets/plotly-2.35.2.min.js");

/// Escape text inserted into HTML markup.
fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// Serialize a value to JSON that is safe to embed inside a script element.
///
/// A kernel name containing `</script>` would otherwise close the element early.
fn script_json<T: serde::Serialize>(value: &T) -> Result<String> {
    Ok(serde_json::to_string(value)?.replace("</", "<\\/"))
}

/// Generate a standalone interactive HTML report using embedded Plotly.js.
pub fn export_html_report<P: AsRef<Path>>(
    trace: &Trace,
    analysis: &TraceAnalysis,
    out_path: P,
) -> Result<()> {
    let out_path = out_path.as_ref();
    let mut file = File::create(out_path)
        .with_context(|| format!("Failed to create HTML report: {}", out_path.display()))?;

    // Determine baseline timestamp in seconds
    let min_ts_ns = trace.time_bounds().map_or(0, |(min, _)| min);

    // One Plotly line per power series
    let timeline_traces: Vec<_> = trace
        .series
        .iter()
        .map(|s| {
            let time_sec: Vec<f64> = s
                .samples
                .iter()
                .map(|p| (p.timestamp_ns.saturating_sub(min_ts_ns)) as f64 / 1_000_000_000.0)
                .collect();
            let power_watts: Vec<f64> = s.samples.iter().map(|p| p.power_watts).collect();
            json!({
                "x": time_sec,
                "y": power_watts,
                "mode": "lines",
                "name": format!("{} {}", s.domain, s.device_id),
                "line": { "width": 2 }
            })
        })
        .collect();

    // Prepare summary bar chart data
    let region_names: Vec<String> = analysis.regions.iter().map(|r| r.name.clone()).collect();
    let region_energies: Vec<f64> = analysis
        .regions
        .iter()
        .map(|r| r.exclusive_energy_joules)
        .collect();

    let app_name = trace
        .metadata
        .as_ref()
        .and_then(|m| m.app_name.as_deref())
        .unwrap_or("Kokkos Application");
    let hostname = trace
        .metadata
        .as_ref()
        .and_then(|m| m.hostname.as_deref())
        .unwrap_or("Unknown Node");

    let app_name = escape_html(app_name);
    let hostname = escape_html(hostname);
    let timeline_traces_json = script_json(&timeline_traces)?;
    let note_html = sampling_note(analysis)
        .map(|note| format!(r#"<p class="note">Note: {note}</p>"#))
        .unwrap_or_default();
    let region_names_json = script_json(&region_names)?;
    let region_energies_json = script_json(&region_energies)?;

    let html_content = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{app_name} - energy-dashboard-for-kokkos</title>
  <script>{plotly_js}</script>
  <style>
    html {{ scrollbar-gutter: stable; }}
    body {{ margin: 0; background: #fff; color: #111; font: 16px/1.5 Charter, Cambria, "Times New Roman", serif; }}
    main {{ max-width: 880px; margin: 0 auto; padding: 32px 16px 48px; }}
    p {{ margin: 0; }}
    h1 {{ margin: 0 0 4px; font-size: 26px; font-weight: normal; line-height: 1.25; }}
    table {{ margin-top: 28px; border-collapse: collapse; border-top: 2px solid #000; border-bottom: 2px solid #000; font-variant-numeric: tabular-nums; }}
    caption {{ text-align: left; padding-bottom: 6px; }}
    th, td {{ padding: 3px 0 3px 24px; text-align: right; font-weight: normal; }}
    th:first-child, td:first-child {{ padding-left: 0; }}
    th {{ border-bottom: 1px solid #000; }}
    .note {{ margin-top: 6px; max-width: 72ch; font-size: 14px; }}
    figure {{ margin: 40px 0 0; overflow-x: auto; break-inside: avoid; }}
    figcaption {{ margin-top: 6px; font-size: 14px; }}
    #barPlot {{ min-width: 640px; }}
    @media (max-width: 480px) {{ table {{ font-size: 14px; }} th, td {{ padding-left: 12px; }} }}
    @media print {{ figure {{ overflow: visible; }} }}
  </style>
</head>
<body>
<main>
  <h1>{app_name}</h1>
  <p>Host: {hostname}. Report generated by energy-dashboard-for-kokkos.</p>

  <table>
    <caption>Run summary.</caption>
    <tr><th>Duration (s)</th><th>Total energy (J)</th><th>Average power (W)</th></tr>
    <tr><td>{duration:.3}</td><td>{total_energy:.2}</td><td>{avg_power:.1}</td></tr>
  </table>
  {note_html}

  <figure>
    <div id="timelinePlot"></div>
    <figcaption>Figure 1. Power draw over time, one line per power series (domain and device).
      Time is counted from the start of the trace.</figcaption>
  </figure>

  <figure>
    <div id="barPlot"></div>
    <figcaption>Figure 2. Exclusive (self) energy per block (n = {num_regions}), largest at the top.
      Exclusive energy leaves out nested child blocks.</figcaption>
  </figure>
</main>

  <script>
    const timelineTraces = {timeline_traces_json};
    const blockNames = {region_names_json};
    const blockEnergies = {region_energies_json};

    // Charts use the font of the page
    const font = {{ family: getComputedStyle(document.body).fontFamily, size: 12, color: '#000' }};
    const grid = {{ showgrid: true, gridcolor: '#c8c8c8', griddash: 'dot' }};
    const config = {{ responsive: true, displaylogo: false, toImageButtonOptions: {{ format: 'svg' }} }};

    // One series: no legend, its name goes in the axis title so SVG exports keep it
    const multi = timelineTraces.length > 1;
    const powerTitle = timelineTraces.length === 1 ? timelineTraces[0].name + ' power (W)' : 'Power (W)';

    function axis(title, extra) {{
      return Object.assign({{
        title: {{ text: title }},
        showline: true,
        linecolor: '#000',
        ticks: 'outside',
        ticklen: 4,
        tickcolor: '#000',
        showgrid: false,
        zeroline: false,
        automargin: true
      }}, extra);
    }}

    function layout(extra) {{
      return Object.assign({{
        font: font,
        paper_bgcolor: '#fff',
        plot_bgcolor: '#fff',
        hoverlabel: {{ bgcolor: '#fff', bordercolor: '#000', font: font }}
      }}, extra);
    }}

    timelineTraces.forEach(function (t) {{
      t.hovertemplate = '%{{y:.1f}} W at %{{x:.3f}} s<extra>%{{fullData.name}}</extra>';
    }});

    Plotly.newPlot('timelinePlot', timelineTraces, layout({{
      height: 360,
      margin: {{ t: multi ? 36 : 12, r: 10, b: 50, l: 60 }},
      colorway: ['#000000', '#b2182b', '#2166ac', '#1b7837', '#8c510a', '#762a83', '#01665e', '#777777'],
      showlegend: multi,
      legend: {{ orientation: 'h', x: 0, y: 1, yanchor: 'bottom' }},
      xaxis: axis('Time (s)'),
      yaxis: axis(powerTitle, Object.assign({{ rangemode: 'tozero' }}, grid))
    }}), config);

    Plotly.newPlot('barPlot', [{{
      type: 'bar',
      orientation: 'h',
      x: blockEnergies,
      y: blockNames,
      marker: {{ color: '#4d4d4d' }},
      texttemplate: '%{{x:.2f}}',
      textposition: 'outside',
      constraintext: 'none',
      cliponaxis: false,
      hovertemplate: '%{{y}}<br>%{{x:.6~g}} J<extra></extra>'
    }}], layout({{
      height: Math.max(160, 70 + 20 * blockNames.length),
      margin: {{ t: 10, r: 60, b: 50, l: 10 }},
      bargap: 0.35,
      xaxis: axis('Exclusive energy (J)', Object.assign({{ rangemode: 'tozero' }}, grid)),
      yaxis: axis('', {{
        categoryorder: 'total ascending',
        // Cut very long names on the axis, the hover label keeps them whole
        tickmode: 'array',
        tickvals: blockNames,
        ticktext: blockNames.map(function (n) {{ return n.length > 72 ? n.slice(0, 69) + '...' : n; }}),
        tickfont: {{ family: 'Menlo, Consolas, monospace', size: 11 }}
      }})
    }}), config);
  </script>
</body>
</html>
"#,
        plotly_js = PLOTLY_JS,
        app_name = app_name,
        hostname = hostname,
        total_energy = analysis.total_trace_energy_joules,
        duration = analysis.total_trace_duration_sec,
        avg_power = analysis.avg_trace_power_watts,
        num_regions = analysis.regions.len(),
        timeline_traces_json = timeline_traces_json,
        note_html = note_html,
        region_names_json = region_names_json,
        region_energies_json = region_energies_json
    );

    file.write_all(html_content.as_bytes())?;
    file.flush()?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::analyze_trace;
    use crate::model::{DeviceDomain, Event, Metadata, PowerSample, RegionCategory};

    #[test]
    fn test_untrusted_names_are_escaped() {
        let metadata = Metadata {
            spec_version: "1.0".to_string(),
            app_name: Some("<b>app</b>".to_string()),
            hostname: None,
            kokkos_backend: None,
            start_epoch_ns: None,
        };
        let event = Event {
            id: 1,
            parent_id: 0,
            name: "</script><b>kernel".to_string(),
            category: RegionCategory::ParallelFor,
            start_ns: 0,
            end_ns: 10,
        };
        let sample = PowerSample {
            timestamp_ns: 0,
            domain: DeviceDomain::Gpu,
            device_id: 0,
            power_watts: 100.0,
            energy_joules: None,
        };
        let trace = Trace::new(Some(metadata), vec![event], vec![sample]);
        let file = tempfile::NamedTempFile::new().unwrap();
        export_html_report(&trace, &analyze_trace(&trace), file.path()).unwrap();

        let html = std::fs::read_to_string(file.path()).unwrap();
        assert!(html.contains("&lt;b&gt;app&lt;/b&gt;"));
        assert!(!html.contains("<b>app"));
        // Only the Plotly bundle and the chart script close a script element
        assert_eq!(html.matches("</script>").count(), 2);
    }
}
