{
 "title": "Energy Analysis Dashboard",
 "tags": [
  "energy",
  "gpu",
  "cpu"
 ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:06.000Z" },
 "panels": [
  { "title": "Data Using Variorum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Over Time (Region Detail)",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT * FROM select_variorum_nonzero();"
    }
   ]
  },
  {
   "title": "Power over Time",
   "type": "xychart",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ms, power_watts FROM variorum_gpus "
    }
   ]
  },
  {
   "title": "Region Timing Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT name, (end_time_ms - start_time_ms) AS \"duration_ms\" FROM variorum_regions"
    }
   ]
  },
  {
   "title": "Table of Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT * FROM variorum_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Data Using NVML Profiler (Power Variant)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Power Over Time (Region Detail)",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT * FROM select_nvml_series_nonzero()"
    }
   ]
  },
  {
   "title": "General Statistics from Tool",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM nvml_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Power over Time (NVML Power)",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT time_relative_ms AS \"Time\", power_watts AS \"Power\" FROM nvml_relative "
    }
   ]
  },
  {
   "title": "Data Using NVML Profiler (Energy Variant) (WIP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "Energy Over Time (Region Detail)",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT * FROM select_nvml_energy_series_nonzero()"
    }
   ]
  },
  {
   "title": "Statistics Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 65 },
   "targets": [
    {
     "rawSql": "SELECT * FROM nvml_energy_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Energy over Time",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT time_relative_ms, energy_joules FROM nvml_energy_relative "
    }
   ]
  }
 ]
}